package com.necromantus.lang;

import java.util.Objects;

public class NMVariable extends Named {
    private Object value;

    public NMVariable(String name, Object value) {
        this.name = name;
        this.value = value;
    }

    public Object getValue() {
        return value;
    }

    public void setValue(Object value) {
        this.value = value;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        NMVariable that = (NMVariable) o;
        return Objects.equals(name, that.name) &&
                Objects.equals(value, that.value);
    }

    // dont really need that but generated by intellij idea.
    @Override
    public int hashCode() {
        return Objects.hash(name, value);
    }
}
